version: '3.2'
services: 
  # kong database
  kong-database:
    image: postgres:9.6
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
    ports: 
      - "5432:5432"
    networks: 
      - kong-net
    restart: on-failure
    #stdin_open: true
    #tty: true
    #volumes:
     #- kong_data:/var/lib/postgresql/data

  # kong migration service 
  kong-migration:
    image: kong
    environment: 
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: kong
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
    networks: 
      - kong-net
    depends_on: 
      - kong-database
      #  condition: service_healty
    command: "kong migrations bootstrap"
    restart: on-failure
  # kong migration service 
  kong:
    image: kong
    environment: 
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: kong
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      #KONG_PG_PASSWORD: kong
      KONG_LOG_LEVEL: debug
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMING_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports: 
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    networks: 
      - kong-net
    depends_on: 
      - kong-database
      - kong-migration
    #    condition: service_healty
    restart: on-failure
networks: 
  kong-net:
    driver: bridge
volumes:
  kong_data: 
